// Sample TMUA questions for demonstration
export const sampleQuestions = [
  // Paper 1 Questions
  {
    paper: 1,
    index: 0,
    stemLatex: 'If $x^2 - 5x + 6 = 0$, what are the possible values of $x$?',
    options: [
      { key: 'A', latex: '$x = 1$ or $x = 6$' },
      { key: 'B', latex: '$x = 2$ or $x = 3$' },
      { key: 'C', latex: '$x = -2$ or $x = -3$' },
      { key: 'D', latex: '$x = 5$ or $x = 1$' },
      { key: 'E', latex: '$x = 6$ or $x = -1$' },
    ],
    answerKey: 'B',
    explanationLatex: 'We can factor $x^2 - 5x + 6$ as $(x-2)(x-3)$. Setting this equal to zero gives $x = 2$ or $x = 3$.',
    tags: ['algebra', 'quadratics'],
    difficulty: 1,
  },
  {
    paper: 1,
    index: 1,
    stemLatex: 'What is the value of $\\frac{2^5 \\times 2^3}{2^4}$?',
    options: [
      { key: 'A', latex: '$2^2$' },
      { key: 'B', latex: '$2^4$' },
      { key: 'C', latex: '$2^6$' },
      { key: 'D', latex: '$2^{12}$' },
      { key: 'E', latex: '$2^8$' },
    ],
    answerKey: 'B',
    explanationLatex: 'Using exponent rules: $\\frac{2^5 \\times 2^3}{2^4} = \\frac{2^{5+3}}{2^4} = \\frac{2^8}{2^4} = 2^{8-4} = 2^4$.',
    tags: ['algebra', 'exponents'],
    difficulty: 1,
  },
  {
    paper: 1,
    index: 2,
    stemLatex: 'A circle has radius $r = 5$. What is its area?',
    options: [
      { key: 'A', latex: '$10\\pi$' },
      { key: 'B', latex: '$25\\pi$' },
      { key: 'C', latex: '$5\\pi$' },
      { key: 'D', latex: '$50\\pi$' },
      { key: 'E', latex: '$\\frac{25\\pi}{2}$' },
    ],
    answerKey: 'B',
    explanationLatex: 'The area of a circle is $A = \\pi r^2 = \\pi(5)^2 = 25\\pi$.',
    tags: ['geometry', 'circles'],
    difficulty: 1,
  },
  {
    paper: 1,
    index: 3,
    stemLatex: 'If $f(x) = 2x + 3$, what is $f(f(1))$?',
    options: [
      { key: 'A', latex: '$5$' },
      { key: 'B', latex: '$7$' },
      { key: 'C', latex: '$10$' },
      { key: 'D', latex: '$13$' },
      { key: 'E', latex: '$11$' },
    ],
    answerKey: 'D',
    explanationLatex: 'First, $f(1) = 2(1) + 3 = 5$. Then $f(f(1)) = f(5) = 2(5) + 3 = 10 + 3 = 13$.',
    tags: ['functions', 'composition'],
    difficulty: 2,
  },
  {
    paper: 1,
    index: 4,
    stemLatex: 'The sum of three consecutive integers is 72. What is the smallest of these integers?',
    options: [
      { key: 'A', latex: '$22$' },
      { key: 'B', latex: '$23$' },
      { key: 'C', latex: '$24$' },
      { key: 'D', latex: '$25$' },
      { key: 'E', latex: '$26$' },
    ],
    answerKey: 'B',
    explanationLatex: 'Let the integers be $n, n+1, n+2$. Then $n + (n+1) + (n+2) = 72$, so $3n + 3 = 72$, giving $3n = 69$ and $n = 23$.',
    tags: ['algebra', 'sequences'],
    difficulty: 2,
  },
  // Generate remaining Paper 1 questions (6-19)
  ...Array.from({ length: 15 }, (_, i) => ({
    paper: 1,
    index: i + 5,
    stemLatex: `Sample question ${i + 6} for Paper 1. If $x = ${i + 2}$, what is $x^2$?`,
    options: [
      { key: 'A', latex: `$${(i + 2) ** 2 - 2}$` },
      { key: 'B', latex: `$${(i + 2) ** 2}$` },
      { key: 'C', latex: `$${(i + 2) ** 2 + 2}$` },
      { key: 'D', latex: `$${(i + 2) ** 2 + 4}$` },
      { key: 'E', latex: `$${(i + 2) * 2}$` },
    ],
    answerKey: 'B',
    explanationLatex: `When $x = ${i + 2}$, we have $x^2 = (${i + 2})^2 = ${(i + 2) ** 2}$.`,
    tags: ['algebra', 'basic'],
    difficulty: 1,
  })),
  
  // Paper 2 Questions
  {
    paper: 2,
    index: 0,
    stemLatex: 'What is the derivative of $f(x) = x^3 + 2x^2 - 5x + 1$?',
    options: [
      { key: 'A', latex: '$3x^2 + 4x - 5$' },
      { key: 'B', latex: '$3x^2 + 2x - 5$' },
      { key: 'C', latex: '$x^2 + 4x - 5$' },
      { key: 'D', latex: '$3x^2 + 4x$' },
      { key: 'E', latex: '$3x + 4x - 5$' },
    ],
    answerKey: 'A',
    explanationLatex: 'Using the power rule: $\\frac{d}{dx}(x^3 + 2x^2 - 5x + 1) = 3x^2 + 4x - 5$.',
    tags: ['calculus', 'derivatives'],
    difficulty: 2,
  },
  {
    paper: 2,
    index: 1,
    stemLatex: 'How many ways can you arrange 5 distinct books on a shelf?',
    options: [
      { key: 'A', latex: '$24$' },
      { key: 'B', latex: '$60$' },
      { key: 'C', latex: '$120$' },
      { key: 'D', latex: '$720$' },
      { key: 'E', latex: '$5$' },
    ],
    answerKey: 'C',
    explanationLatex: 'The number of permutations of 5 distinct objects is $5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120$.',
    tags: ['combinatorics', 'permutations'],
    difficulty: 2,
  },
  {
    paper: 2,
    index: 2,
    stemLatex: 'If $\\log_2(x) = 5$, what is $x$?',
    options: [
      { key: 'A', latex: '$10$' },
      { key: 'B', latex: '$25$' },
      { key: 'C', latex: '$32$' },
      { key: 'D', latex: '$64$' },
      { key: 'E', latex: '$128$' },
    ],
    answerKey: 'C',
    explanationLatex: 'If $\\log_2(x) = 5$, then $x = 2^5 = 32$.',
    tags: ['logarithms', 'algebra'],
    difficulty: 2,
  },
  {
    paper: 2,
    index: 3,
    stemLatex: 'What is the sum of the first 10 positive integers?',
    options: [
      { key: 'A', latex: '$45$' },
      { key: 'B', latex: '$50$' },
      { key: 'C', latex: '$55$' },
      { key: 'D', latex: '$60$' },
      { key: 'E', latex: '$65$' },
    ],
    answerKey: 'C',
    explanationLatex: 'The sum is $1 + 2 + 3 + \\ldots + 10 = \\frac{10 \\times 11}{2} = 55$.',
    tags: ['sequences', 'series'],
    difficulty: 1,
  },
  {
    paper: 2,
    index: 4,
    stemLatex: 'In a right triangle, if one leg is 3 and the hypotenuse is 5, what is the other leg?',
    options: [
      { key: 'A', latex: '$2$' },
      { key: 'B', latex: '$4$' },
      { key: 'C', latex: '$\\sqrt{34}$' },
      { key: 'D', latex: '$6$' },
      { key: 'E', latex: '$8$' },
    ],
    answerKey: 'B',
    explanationLatex: 'Using the Pythagorean theorem: $a^2 + 3^2 = 5^2$, so $a^2 + 9 = 25$, giving $a^2 = 16$ and $a = 4$.',
    tags: ['geometry', 'pythagorean'],
    difficulty: 2,
  },
  // Generate remaining Paper 2 questions (6-19)
  ...Array.from({ length: 15 }, (_, i) => ({
    paper: 2,
    index: i + 5,
    stemLatex: `Sample question ${i + 6} for Paper 2. What is the value of $${i + 3} \\times 2$?`,
    options: [
      { key: 'A', latex: `$${(i + 3) * 2 - 2}$` },
      { key: 'B', latex: `$${(i + 3) * 2}$` },
      { key: 'C', latex: `$${(i + 3) * 2 + 2}$` },
      { key: 'D', latex: `$${(i + 3) * 3}$` },
      { key: 'E', latex: `$${(i + 3) + 2}$` },
    ],
    answerKey: 'B',
    explanationLatex: `$${i + 3} \\times 2 = ${(i + 3) * 2}$.`,
    tags: ['arithmetic', 'basic'],
    difficulty: 1,
  })),
]
